{
    "dist": {
        "segment.scad": {
            "vars": ["Inner_Diameter"],
            "stl": {
                "segment-100mm.stl": [100]
            }
        },
        "magnetic-parts.scad": {
            "vars": [
                "Inner_Diameter",
                "Model_Type",
                "Connector_Type",
                "Plate_Type",
                "Grommet_Diameter",
                "Magnet_Holes",
                "Screw_Holes",
                "Screw_Hole_Chamfer"
            ],
            "stl": {
                "120mm-fan-grommet-100mm.stl": [100, 1, 1, 1, 120, 0, 1, 0],
                "120mm-fan-grommet-100mm-magnets.stl": [100, 1, 1, 1, 120, 1, 1, 0],
                "120mm-fan-connector-100mm-male.stl": [100, 0, 1, 1, 120, 0, 1, 0],
                "120mm-fan-connector-100mm-magnets-male.stl": [100, 0, 1, 1, 120, 1, 1, 0],
                "magnetic-connector-100mm-male.stl": [100, 0, 1, 0, 101.6, 1, 0, 0],
                "magnetic-connector-100mm-female.stl": [100, 0, 2, 0, 101.6, 1, 0, 0],
                "magnetic-plate-100mm.stl": [100, -1, 1, 0, 101.6, 1, 1, 1],
                "magnetic-grommet-100mm.stl": [100, 1, 1, 0, 101.6, 1, 1, 1]
            }
        },
        "vacuum-attachment.scad": {
            "vars": ["Inner_Diameter", "Connector_Type"],
            "stl": {
                "vacuum-attachment-100mm.stl": [100, 2]
            }
        }
    },
    "images": {
        "demo.png": {
            "model": "demo.scad",
            "view_options": "axes,scales",
            "vars": ["Inner_Diameter"],
            "values": [[100]]
        }
    }
}
