---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: 🛠️ Install tools
        run: |
          sudo apt install -y openscad xvfb
          pip install scons

      - name: 🏗️ Build
        run: xvfb-run scons ref="${GITHUB_BASE_REF}"

      - name: 📦 Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "Rendered Models"
          path: |
            build/*
            !build/**/*.deps

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
